### PR TITLE
feat(samples): add good-first-issue.story (gfs.story)

### PR DESCRIPTION
**Pull request by adnrs96**
I am adding a new example which works given we merge https://github.com/oms-services/github/pull/8

I have tested things out by using a copy of the service called `adnrs96/githubms` which is on the hub

Also after the tweet is posted currently the runtime doesn't handle the responce from twitter very well but that doesn't break the story itself so I created the PR.

### CODE REVIEW

**Comment by adnrs96** [comment]
AT the moment this won't pass the test from github actions since the PR from the omg-services isn't merged yet

**Comment by adnrs96** [comment]
I also added the icons which I downloaded from https://about.twitter.com/en_us/company/brand-resources.html and https://github.com/logos

Github one did require to be converted to SVG which I did locally using `convert` tool

**Comment by williammartin** [comment]
Cheers Aditya. We're definitely going to want this as one of the featured cards but as we're iterating on the playground itself in the next few days, we'll probably hold off on merging.

**Comment by adnrs96** [comment]
Sure, no worries. Just ping me and I will be happy to update the PR.

**Comment by JeanBarriere** [comment]
We'll be adding more examples when we'll be implementing graphQL and pulling them from a database. For now, closing this PR and referencing it [here](https://www.pivotaltracker.com/story/show/169919867)

**Pull request closed without merging**
